name: Package - Automatic Versioning using Semantic & Build Image then push to registry.
on:
  workflow_dispatch

jobs:
  semantic-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Semantic Release
        id: semantic
        uses: sepulsa/semantic-release-action@v2
        with:
          semantic_version: 16.0.4
          branches: |    
            [
              'main', 
              'hotfix/**', 
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
